# Generated by Django 4.2.27 on 2025-12-24 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scenario_type', models.CharField(choices=[('optimistic', 'Optimistic'), ('realistic', 'Realistic'), ('pessimistic', 'Pessimistic'), ('custom', 'Custom')], default='realistic', max_length=20)),
                ('initial_investment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_return_rate', models.DecimalField(decimal_places=2, help_text='Expected annual return percentage', max_digits=5)),
                ('investment_period_years', models.IntegerField(help_text='Investment period in years')),
                ('inflation_rate', models.DecimalField(decimal_places=2, default=2.5, help_text='Annual inflation rate percentage', max_digits=5)),
                ('volatility', models.DecimalField(decimal_places=2, default=0, help_text='Expected volatility percentage', max_digits=5)),
                ('projected_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_contributions', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_gains', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contributions_to_date', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gains_to_date', models.DecimalField(decimal_places=2, max_digits=15)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='forecaster.scenario')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('scenario', 'year')},
            },
        ),
    ]
