# Generated by Django 4.2.27 on 2025-12-24 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forecaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alert_type', models.CharField(choices=[('milestone', 'Milestone Reached'), ('goal', 'Investment Goal'), ('threshold', 'Value Threshold'), ('roi', 'ROI Target'), ('reminder', 'Periodic Reminder')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('triggered', 'Triggered'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, help_text='Target portfolio value', max_digits=15, null=True)),
                ('target_roi', models.DecimalField(blank=True, decimal_places=2, help_text='Target ROI percentage', max_digits=5, null=True)),
                ('reminder_frequency_days', models.IntegerField(blank=True, help_text='Days between reminders', null=True)),
                ('message', models.TextField(help_text='Custom alert message')),
                ('send_email', models.BooleanField(default=False, help_text='Send email notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('next_reminder', models.DateTimeField(blank=True, null=True)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='forecaster.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('alert', 'Alert'), ('info', 'Information'), ('warning', 'Warning'), ('success', 'Success')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='forecaster.alert')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forecaster.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
